import csv
import numpy as np
import pandas as pd
from pathlib import Path

class FileIO:
    
    """
        scope:
            takes the path to a *single* (?) csv and returns a pandas dataframe with
            units properly adjusted and labeled
            
            (1) open the csv file at specified path
            (2) check if csv file has headers on the first line
            (3) uses pandas to read csv file
                (i) if headers are in the file or given as argument, use those
                (i) if no headers, then use check_xyz methods to create some
            
    
    """
    def __init__(self, df_headers=None, verbose=True):
        self.df_headers = df_headers
        self.verbose = verbose
        
        
    def load_df(self, df:pd.DataFrame):
        if isinstance(df, pd.DataFrame) is False:
            raise TypeError
        pass

    def load_csv(self, pathlib_filepath:Path):
        """
            filepath -> should be a pathlib.Path object
            self.filepath -> saved as a string, ideally generated by pathlib
                                so it can be easily converted back with 
                                filepath_obj = Path(self.filepath)
        """
        
        # check if argument is a pathlib.Path object
        if isinstance(pathlib_filepath, Path) is False:
            # if not a Path, try to turn it into one
            try:
                self.filepath = Path(pathlib_filepath)
            except:
                self.filepath = pathlib_filepath  # just hope for the best if it fails I guess
        else: 
            # if it is a Path, save the string version into self.filepath
            self.filepath = str(pathlib_filepath.resolve())
        
        self.filename = pathlib_filepath.name
        
        # if there is a set of headers, use those, otherwise let pandas grab from file
        if self.df_headers is None:
            self.df = pd.read_csv(self.filepath, index_col=0)
            self.df_headers = self.df.columns
        else: 
            # make sure to skip the first row of headers if we have our own
            self.df = pd.read_csv(self.filepath, names=self.df_headers, skiprows=1, index_col=0)
        
        self.var_list = [col for col in self.df]

        if self.verbose is True:
            print("Successfully loaded csv file into FileIO - displaying all variables and dataframe itself")
            display(self.var_list)
            display(self.df)
            
    def generate_headers():
        pass
    
    def check_for_header():
        pass
    
    def check_phase_units():
        pass
    
    def check_s21_units():
        pass
    
    # TODO: detect dB vs lin units
    # TODO: detect rads vs deg
    # TODO: detect Hz vs GHz